# Generated by Django 3.0.7 on 2020-07-08 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompreference',
            name='maximumbudget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='roompreference',
            name='minimumbudget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
