# Generated by Django 3.0.7 on 2020-07-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0004_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompreference',
            name='rules',
            field=models.ManyToManyField(to='flatapp.Rules'),
        ),
    ]
