# Generated by Django 3.0.7 on 2020-07-08 09:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0005_roompreference_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 8))]),
        ),
    ]
