# Generated by Django 3.0.7 on 2020-07-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0006_auto_20200708_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompreference',
            name='propertyamenities',
            field=models.ManyToManyField(related_name='propertyamenities', to='flatapp.PropertyAmenities'),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='rules',
            field=models.ManyToManyField(related_name='roompreference', to='flatapp.Rules'),
        ),
    ]
