# Generated by Django 3.0.7 on 2020-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0007_auto_20200708_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompreference',
            name='rules',
            field=models.ManyToManyField(related_name='rules', to='flatapp.Rules'),
        ),
    ]
