# Generated by Django 2.1.1 on 2020-07-14 10:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0008_auto_20200708_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompreference',
            name='checked',
            field=models.NullBooleanField(choices=[(None, 'I do not know now'), (True, 'Yes I acknowledge this'), (False, 'No, I do not like this')]),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 14))]),
        ),
    ]
