# Generated by Django 2.1.1 on 2020-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0009_auto_20200714_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompreference',
            name='checked',
            field=models.NullBooleanField(choices=[(None, 'Null'), (True, 'True'), (False, 'False')], default=None),
        ),
    ]
