# Generated by Django 2.1.1 on 2020-07-15 10:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0010_auto_20200714_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('plan_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='roompreference',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 15))]),
        ),
    ]
