# Generated by Django 2.1.1 on 2020-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0011_auto_20200715_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_id',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
