# Generated by Django 2.1.1 on 2020-07-16 10:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0014_user_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid',
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 16))]),
        ),
    ]
