# Generated by Django 2.1.1 on 2020-07-16 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0015_auto_20200716_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.CharField(choices=[('No Plan Chosen', 'No Plan Chosen'), ('Plan Activated', 'Plan Activated'), ('Plan Expired', 'Plan Expired')], default='No Plan Chosen', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_validity',
            field=models.IntegerField(default=0),
        ),
    ]
