# Generated by Django 2.1.1 on 2020-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0017_auto_20200716_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
