# Generated by Django 2.1.1 on 2020-07-17 08:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0020_auto_20200716_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 17))]),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flatapp.Payment'),
        ),
    ]
