# Generated by Django 2.1.1 on 2020-07-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0021_auto_20200717_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_validity',
        ),
    ]
