# Generated by Django 2.1.1 on 2020-07-18 10:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0022_auto_20200717_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('No Plan Chosen', 'No Plan Chosen'), ('Plan Activated', 'Plan Activated'), ('Plan Expired', 'Plan Expired')], default='No Plan Chosen', max_length=30),
        ),
        migrations.AlterField(
            model_name='roompreference',
            name='moveindate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2020, 7, 18))]),
        ),
    ]
