# Generated by Django 2.1.1 on 2020-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatapp', '0023_auto_20200718_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
